### PR TITLE
Allow facility override in options

### PR DESCRIPTION
**Pull request by rnewson**
BugzID: 32072

### CODE REVIEW

**Comment by rnewson** [comment]
This will allow us to send security events to fail2ban, splunk and qradar directly from dbcore (auth and authpriv facilities). For lager, we can configure multiple backends to achieve the same goal.

cc @mwhite

**Comment by mwhite** [comment]
I think you meant to CC someone else :)

**Comment by rnewson** [comment]
haha, oops :)

**Comment by rnewson** [comment]
cc the real @mattwhite :P

**Comment by iilyak** [comment]
Looks legit to me.

**Comment by rnewson** [comment]
holding on this for a bit, will see whether we can get the logs out with a bit of rsyslog config first

**Pull request merged**
